old_sound_rabbit_mq:
    connections:
        default:
            host:     'rabbitmq'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: true # default false
    producers:
        send_email:
            connection:       default
            exchange_options: {name: 'send_email', type: direct}
            service_alias: app_send_email_service
            class: App\Producer\SendEmailProducer
    consumers:
        send_email:
            connection:       default
            exchange_options: {name: 'send_email', type: direct}
            queue_options:    {name: 'send_email'}
            callback:         app.consumer.send_email